name: Build HackedServer
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        # ضفنا السطر ده عشان يتجاهل مكان الـ pom.xml ويجيبه أينما كان
        run: mvn clean package -DskipTests -f $(find . -name pom.xml | head -n 1)

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: HackedServer-Artifact
          path: "**/target/*.jar"
