name: Build HackedServer Ultimate
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # تحديث ليتوافق مع سيرفرك الحديث
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          POM_PATH=$(find . -name "pom.xml" | head -n 1)
          mvn clean package -DskipTests -f "$POM_PATH"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HackedServer-Final-Pack
          # السطر ده هيرفع لك كل ملفات الـ Jar اللي طلعت في Spigot و Velocity
          path: "**/target/*.jar"
